apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-labs
  labels:
    app: jupyter-labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-labs
  template:
    metadata:
      labels:
        app: jupyter-labs
    spec:
      serviceAccountName: spark-sa  # assign service account name
      containers:
        - name: jupyter-labs
          image: jupyter/pyspark-notebook:python-3.10 # use python3.10 version which is compatible with spark-3.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
      imagePullSecrets:
        - name: docker-registry-secret # give image pull secrets
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-labs
  labels:
    app: jupyter-labs
spec:
  ports:
    - protocol: TCP
      port: 29413
  selector:
    app: jupyter-labs
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-labs-ui
  labels:
    app: jupyter-labs-ui
spec:
  ports:
    - protocol: TCP
      port: 8888
  selector:
    app: jupyter-labs
  type: NodePort # Node port: you can specify the port here
