version: "3.6"
services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 9999:8888
      - 4040:4040
    volumes:
      - ${PWD}/jupyter-workspace:/opt/workspace
      - ${PWD}/logs:/opt/spark/logs
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 9090:8080
      - 7077:7077
    volumes:
      - ${PWD}/jupyter-workspace:/opt/workspace
      - ${PWD}/logs:/opt/spark/logs
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 9091:8081
    volumes:
      - ${PWD}/jupyter-workspace:/opt/workspace
      - ${PWD}/logs:/opt/spark/logs
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 9092:8081
    volumes:
      - ${PWD}/jupyter-workspace:/opt/workspace
      - ${PWD}/logs:/opt/spark/logs
    depends_on:
      - spark-master
