version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.type==sparkmaster]
    networks:
      - spark-net
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 4040:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.type==sparkmaster]
    networks:
      - spark-net
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 4041:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.type==sparkworker]
    networks:
      - spark-net
