version: '3.8'

services:
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 980:80
    environment:
      - REGISTRY_URL='https://docker.seegene.com'
    container_name: registry-ui
