apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-storage-pvc
  namespace: docker
spec:
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
