apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker
  labels:
    app: docker-registry-service
spec:
  type: NodePort
  ports:
  - name: docker-port
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31000
  selector:
    app: docker-registry-service
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: docker
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31080
  selector:
    app: docker-registry-service